### ISSUE TITLE
AWS Linux-Ubuntu - and Layers

### ISSUE THREAD

**Issue by pkasson** [swift-sprinter/aws-lambda-swift-sprinter#23]
@Andrea-Scuderi - came over to your repo from your earlier update from tonisuter/aws-lambda-swift.

Your doc says AWS Linux does not support Swift ... but Ubuntu does.

Do you have a quick start to upload the Layer into Lambda to start using this without all the building required before use ?

**Comment by Andrea-Scuderi** [comment]
Yes, I prepared this tutorial: 
https://medium.com/better-programming/how-to-work-with-aws-lambda-in-swift-28326c5cc765
I hope this can help you.

Look also at all the section of the README.
If you find something unclear, please point it out, so we can improve the documentation.

The tool overcame this issue by building the layer and the lambda in Ubuntu and then packaging the build to run on AWS Lambda.

**Comment by Andrea-Scuderi** [comment]
If you don't have much time I have prepared a video: https://youtu.be/C8eE10HbK-I

**Comment by pkasson** [comment]
Awesome - I will take a look at these things - thanks !
