### ISSUE TITLE
Build Swift 5.1 Release on Docker amazonlinux:2018.03

### ISSUE THREAD

**Issue by Andrea-Scuderi** [swift-sprinter/aws-lambda-swift-sprinter#6]
**Provide a Docker file to build Swift 5.1 on Docker amazonlinux:2018.03**
The AWS Lambda Custom Runtime for Swift should be built on Docker amazonlinux:2018.03, the current solution uses the Swift docker images based on Ubuntu.

Solving this could help to:
- Reduce AWS Lambda Custom Runtime for Swift size
- Could solve the HTTPS issue with the CURL library
- Improve the debugging
- Improve the deployment

**The solution is a fix to this broken Dockerfile:**

`Dockerfile`:
```
FROM amazonlinux:2018.03 as builder

RUN yum update && yum -y group install "development tools" && \
    yum -y install ninja-build clang python \
    libuuid-devel libicu-devel libicu-devel libstdc++-devel \
    libedit-devel libxml2-devel sqlite-devel swig python26-devel ncurses-devel \
    pkgconfig openssl-devel systemtap-sdt-devel tzdata rsync git wget

#cmake
WORKDIR /tmp
RUN wget https://cmake.org/files/v3.15/cmake-3.15.0.tar.gz
RUN tar -xvf cmake-3.15.0.tar.gz
WORKDIR /tmp/cmake-3.15.0
RUN ./bootstrap
RUN make
RUN make install

RUN mkdir /swift-source
WORKDIR /swift-source
RUN git clone https://github.com/apple/swift.git
RUN ./swift/utils/update-checkout --clone
RUN ./swift/utils/update-checkout --tag swift-5.1-RELEASE
RUN ./swift/utils/build-script --preset=buildbot_linux installable_package=$ROOT_DIR/swift-package.tar.gz install_destdir=/tmp/swift
```

**Pull request details**
The Docker file must be under the path `docker/amazonlinux-2018.03`

**Comment by algal** [comment]
I made some progress with this but did not get there:

I've added inline comments to explain the changes. But this still fails because of having a too old version of libstdc++.

```
FROM amazonlinux:2018.03 as builder

RUN yum -y update # need -y for this to complete unattended
RUN yum -y group install "development tools"
RUN yum -y install ninja-build clang python \
    libuuid-devel libicu-devel libicu-devel libstdc++-devel \
    libedit-devel libxml2-devel sqlite-devel swig python26-devel ncurses-devel \
    pkgconfig openssl-devel systemtap-sdt-devel tzdata rsync git wget

#cmake
WORKDIR /tmp
RUN wget https://cmake.org/files/v3.15/cmake-3.15.0.tar.gz
RUN tar -xvf cmake-3.15.0.tar.gz
WORKDIR /tmp/cmake-3.15.0
RUN ./bootstrap
RUN make
RUN make install

RUN mkdir /swift-source
WORKDIR /swift-source
RUN git clone https://github.com/apple/swift.git
RUN ./swift/utils/update-checkout --clone
#RUN ./swift/utils/update-checkout --tag swift-5.1-RELEASE # will not build, since needs the following commit to build: https://github.com/apple/swift/commit/91e0db40b62069d7e4c98ac06a9f172951b4eb5e
RUN ./swift/utils/update-checkout --tag swift-DEVELOPMENT-SNAPSHOT-2019-11-29-a
RUN ./swift/utils/build-script --preset=buildbot_linux installable_package=$ROOT_DIR/swift-package.tar.gz install_destdir=/tmp/swift
```

**Comment by fabianfett** [comment]
@algal I feel your pain in trying to compile on 2018.3. I made it as far as you did. But since the world seems to be great Swift libraries compiled on Amazon Linux 2 also run on 2018.3. 

https://forums.swift.org/t/aws-lambda-runtime-api/18498/37?u=fabianfett

**Comment by Andrea-Scuderi** [comment]
Refer to Swift forums for more info on linux distribution support and the support for Amazon Linux2: [https://forums.swift.org/t/official-platform-support-for-other-linux-distributions-and-a-case-for-amazon-linux-2/33167](https://forums.swift.org/t/official-platform-support-for-other-linux-distributions-and-a-case-for-amazon-linux-2/33167)

@fabianfett thanks for putting forward the case, feel free to add PR to an experimental branch with your amazon linux 2 docker, hopefully your approach in building Amazon Linux 2 will be officially supported.

**Comment by Andrea-Scuderi** [comment]
There is an official version of amazonlinux2.
```docker pull swiftlang/swift:nightly-amazonlinux2```
