### ISSUE TITLE
Performance improvement investigation

### ISSUE THREAD

**Issue by Andrea-Scuderi** [swift-sprinter/aws-lambda-swift-sprinter#8]
**Investigation**
It's required to better understand, in terms of performance, the AWS Lambda Custom Runtime with Swift.

It's required to provide solution to reduce the `Initalization` time and the `Overhead` time that you can monitor when X-Ray is enabled.
![Screenshot 2019-10-03 at 11 25 14](https://user-images.githubusercontent.com/8319309/66119947-a7f09c00-e5d1-11e9-8436-e9dbb612ff9f.png)

It could be helpful if you can comment this with ideas.

**Comment by ballwood** [comment]
I believe the init stage depends on how big the lambda layer is as it has to pull it from s3, can try stripping stuff from the runtime.

**Comment by Andrea-Scuderi** [comment]
@ballwood Yes, I agree, it's the reason I want to have the build of Swift on amazonlinux #5 #6. This could reduce the size of it. The second time you launch the lambda this is zero.
![Screenshot 2019-10-03 at 13 43 25](https://user-images.githubusercontent.com/8319309/66127580-ef802380-e5e3-11e9-974d-2d6ba4415ffd.png)
What is quite obscure, it is the `Overhead` meaning.

**Comment by ballwood** [comment]
might be overhead from x-ray whilst it sends the profiling information?

**Comment by Andrea-Scuderi** [comment]
The investigation it's closed.
Read the results here:
https://medium.com/better-programming/swift-on-aws-lambda-performs-like-node-and-python-using-swift-sprinter-d920521130f1
